import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useAuthContext } from '../context/authcontext'
import OrderList from '../components/ordersList'
import { GetOrdersByUserService, DeleteOrder } from '../services/orderservice';
import OrderForm from '../components/OrderForm';
import _ from 'lodash';

export default function Home() {

  const [orders, setOrders] = useState([]);
  const { state } = useAuthContext();
  const [isEdit, setIsEdit] = useState(false);
  const [record, setRecord] = useState(null);

  const handleDelete = async (id) => {
    var response = await DeleteOrder(id, state.user?.id);
    setOrders(response);

  }

  const handleUpdate = (id) => {

    var record = _.find(orders, { id: id });
    console.log(record);
    setRecord(record);
    setIsEdit(true);
  }



  useEffect(() => {

    const getOrderData = async () => {
      if (state?.user) {
        var response = await GetOrdersByUserService(state.user?.id)
        setOrders(response);
      }
    }
    getOrderData();
  }, [state])

  return (
    <div className={styles.container}>
      <Head>
        <title>Order Management</title>
        <meta name="description" content="Generated by Orders" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className={styles.title}>
        Order Management App
      </h2>
      <p className={styles.description}>
        Hello Mr {state.user?.name}

      </p>

      <div className={styles.grid}>

        <div>
          <OrderForm record={record} isEdit={isEdit} setIsEdit={setIsEdit} setRecord={setRecord} setOrders={setOrders}></OrderForm>
        </div>
        <div>
          <OrderList data={orders} handleDelete={handleDelete} handleUpdate={handleUpdate}></OrderList>
        </div>



      </div>

    </div >
  )
}
